services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      SA_PASSWORD: "LojaManoel@2025"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P LojaManoel@2025 -Q 'SELECT 1'"]
      interval: 10s
      retries: 5

  api:
    build:
      context: .
      dockerfile: src/LojaSeuManoel.Api/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - sqlserver
